version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - minio_network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"      # API S3 do MinIO
      - "9090:9090"      # Console do MinIO
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_SERVER_URL=http://localhost:9000
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:9090
      - TZ=America/Sao_Paulo
    command: server --console-address ":9090" /data
    volumes:
      - minio-data:/data
      - ./create-bucket.sh:/create-bucket.sh
    networks:
      - minio_network
    extra_hosts:
      - "minio:127.0.0.1"
    entrypoint: sh -c "/create-bucket.sh & /usr/bin/docker-entrypoint.sh server --console-address ':9090' /data"

  minio_api:
    build: .
    container_name: minio_api
    depends_on:
      - mysql
      - minio
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=test
      - SERVER_PORT=8080
      - TZ=America/Sao_Paulo
    ports:
      - "1000:8080"
    networks:
      - minio_network

volumes:
  minio-data:
  mysql-data:

networks:
  minio_network:
    driver: bridge
