# MinIO para produção (remoto)
minio:
  url: ${MINIO_URL:http://your-minio-server-url}
  access:
    key: ${MINIO_ACCESS_KEY:prod_access_key}
  secret:
    key: ${MINIO_SECRET_KEY:prod_secret_key}
  bucket:
    name: ${MINIO_BUCKET_NAME:prod-bucket}

# Banco de dados MySQL para produção
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

# Habilitar SSL para ambiente de produção
server:
  ssl:
    enabled: true
