spring:
  application:
    name: MinIO_API
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  profiles:
    active: dev

app:
  api:
    key: ${API_KEY:123}
logging:
  level:
    io.minio: TRACE


server:
  port: ${SERVER_PORT:8080}
#  ssl:
#    key-store: ${SERVER_SSL_KEY_STORE:classpath:keystore.p12}
#    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD:123456}
#    key-store-type: ${SERVER_SSL_KEY_STORE_TYPE:PKCS12}
#    key-alias: ${SERVER_SSL_KEY_ALIAS:minio-api}
