spring:
  datasource:
    url: jdbc:mysql://localhost:${TESTCONTAINERS_MYSQL_PORT}/testdb
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always

server:
  ssl:
    enabled: false

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access:
    key: minioadmin
  secret:
    key: minioadmin
  bucket:
    name: test-bucket
