minio:
  url: ${MINIO_URL:http://localhost:9000}
  access:
    key: ${MINIO_ACCESS_KEY:minioadmin}
  secret:
    key: ${MINIO_SECRET_KEY:minioadmin}
  bucket:
    name: ${MINIO_BUCKET_NAME:dev-bucket}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

#server:
#  ssl:
#    enabled: true
