minio:
  url: ${MINIO_URL:http://localhost:9000}
  access:
    key: ${MINIO_ACCESS_KEY:minioadmin}
  secret:
    key: ${MINIO_SECRET_KEY:minioadmin}
  bucket:
    name: ${MINIO_BUCKET_NAME:test-bucket}

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/testdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${SPRING_DATASOURCE_USERNAME:test}
    password: ${SPRING_DATASOURCE_PASSWORD:test}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
